name: ai-code-review
run-name: ${{ github.actor }} is using AI to do code review for their code
on: [pull_request]
jobs:
  build-go-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go run hello.go

      - name: Get changed js files excluding the docs folder
        id: changed-go-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.go
      
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
