name: ai-code-review
run-name: ${{ github.actor }} is using AI to do code review for their code
on: [pull_request]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build-go-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go run hello.go

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: "Run Code Review script"
        run: python ./.github/scripts/hello.py
        env:
          GIT_REPO: ${{ GITHUB_REPOSITORY }}
          PR_NUMBER: ${{ PR_NUMBER }}
          GITHUB_API_KEY: ${{ secrets.GH_API_KEY }}
